#!/usr/bin/env bash

sh $ZSH/tools/uninstall.sh
chsh -s `which bash`
brew uninstall zsh
brew uninstall stow
brew uninstall neovim
brew uninstall mongosh
brew uninstall go

brew uninstall n

rm ~/.zshrc
rm ~/.picnicrc
rm ~/.tmux.conf
rm ~/.ideavimrc
rm ~/.gitconfig
rm -rf ~/.config/nvim
rm -rf ~/.config/alacritty
rm -rf ~/.config/yabai
rm -rf ~/.config/skhd
rm -rf ~/.local/bin
rm -rf ~/.n

find ~/.local/bin -maxdepth 1 -type l -delete
