#!/usr/bin/env bash

sh $ZSH/tools/uninstall.sh
chsh -s `which bash`
brew uninstall zsh
brew uninstall stow
brew uninstall neovim

rm ~/.zshrc
rm ~/.picnicrc
rm ~/.tmux.conf
rm ~/.ideavimrc
rm ~/.gitconfig
rm -rf ~/.config/nvim
rm -rf ~/.config/alacritty
rm -rf ~/.config/yabai
rm -rf ~/.config/skhd
rm -rf ~/.local/bin

find ~/.local/bin -maxdepth 1 -type l -delete

