#!/usr/bin/env bash

set -eEuo pipefail

echo "Configuring SDKMAN..."
# # Setup SDKMAN
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

echo "Configuring Pyenv..."
export PYENV_ROOT="$HOME/.pyenv"
[[ -d "$PYENV_ROOT/bin" ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

echo "Configuring NVM..."
export NVM_DIR="$HOME/.config/nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"

echo "Installing java with SDKMAN..."
sdk install java 21.0.5-graal
sdk use java 21.0.5-graal

echo "Installing mvnd with SDKMAN..."
sdk install mvnd 1.0.2
sdk use mvnd 1.0.2

echo "Installing python 3.12 with pyenv..."
pyenv install --skip-existing 3.12
pyenv global 3.12

echo "Installing node 20.19.0 with nvm..."
nvm install 20.19.0
nvm use 20.19.0
npm install --global yarn

echo "Creating Obsidian Claude symlink..."
# Get the absolute path to the directory where the script is located
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
cp -f "$SCRIPT_DIR/ai_instructions/OBSIDIAN_CLAUDE.md" "$HOME/Documents/obsidian_notes/CLAUDE.md"
