- hosts: localhost
  become: false

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check
      when: ansible_facts['os_family'] == "Darwin"
      tags:
        - always

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when:
        - ansible_facts['os_family'] == "Darwin"
      tags:
        - always

    - name: Updating apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      when:
        - ansible_facts['os_family'] == "Debian"
      tags:
        - always

    - name: Include Child Task
      import_tasks: tasks/zsh.yml

    - name: Include Child Task
      import_tasks: tasks/utils.yml

    - name: Include Child Task
      import_tasks: tasks/node.yml

    - name: Install stow (Darwin)
      homebrew:
        name: stow
        state: present
      when:
        - ansible_facts['os_family'] == "Darwin"
      tags:
        - dotfiles

    - name: Link dotfiles with GNU stow
      shell: ./install-dotfiles
      tags:
        - dotfiles
