- name: Install zsh (Darwin)
  homebrew:
    name: zsh
    state: present
  when:
    - ansible_facts['os_family'] == "Darwin"
  tags:
    - zsh

- name: Install zsh (Debian)
  apt: name=zsh
  when:
    - ansible_facts['os_family'] == "Debian"
  tags:
    - zsh

- name: Check if shell is zsh
  shell: "echo $SHELL"
  register: myshell
  changed_when: false
  tags:
    - zsh

- name: Change default shell to zsh
  become: true
  shell: "chsh -s $(which zsh) {{ ansible_user_id }}"
  when: '"zsh" not in myshell.stdout'
  tags:
    - zsh

- name: Check if oh-my-zsh is already installed
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh
  tags:
    - zsh

- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh.stat.exists
  tags:
    - zsh

- name: Remove default .zshrc
  file:
    path: "~/.zshrc"
    state: absent
  tags:
    - zsh

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags:
    - zsh

- name: Install diff-so-fancy
  ansible.builtin.git:
    repo: 'https://github.com/so-fancy/diff-so-fancy.git'
    dest: "~/.local/share/diff-so-fancy"
  tags:
    - zsh
