- hosts: localhost
  become: false

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check
      when: ansible_facts['os_family'] == "Darwin"


  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when:
        - ansible_facts['os_family'] == "Darwin"
        - homebrew_check.stat.exists

    - name: Updating apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      when:
        - ansible_facts['os_family'] == "Debian"

    - name: Install zsh (Darwin)
      homebrew:
        name: zsh
        state: present
      when:
        - ansible_facts['os_family'] == "Darwin"
        - homebrew_check.stat.exists

    - name: Install zsh (Debian)
      apt: name=zsh
      when:
        - ansible_facts['os_family'] == "Debian"

    # XXX Check if zsh was installed and add retry block
    - name: Change shell
      shell: chsh -s `which zsh`

    - name: Install ohmyzsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: Install Neovim (Debian)
      apt: name=neovim
      when:
        - ansible_facts['os_family'] == "Debian"

    # - name: Install zsh autosuggestions plugin
    #   ansible.builtin.git:
    #     repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    #     dest: "~/oh-my-zsh/plugins/zsh-autosuggestions"

